### ISSUE TITLE
App crashing on Android SDK 19

### ISSUE THREAD

**Issue by slvtrs** [blackuy/react-native-twilio-video-webrtc#106]
Thanks for all the amazing work. This is a fantastic module that we're excited to use, we're just hitting a wall currently with older Android devices and would greatly appreciate insight.

### Steps to reproduce
1. Include module
2. Build targetSdkVersion 27, minSdkVersion 19.
3. Launch app on Android device or emulator running SDK 19 (SDK 20-22 untested).

### Actual behaviour
App gets stuck in splash screen loop:
1. App's splash screen appears.
2. The "app switching animation" is triggered, as if a different app was coming to the foreground.
3. Splash screen re-appears.
4. The screen alternates between black and the splash screen, about 15 times or so until the app crashes.

#### Notes
* The app launches fine on iOS and on Andoird SDK 23+.
* There seem to be no errors relevant to "twilio," yet this issues disappears if the react-native-twilio-video-webrtc module is removed. Perhaps the issue comes from a dependency of the module?
* The only other modules I've included are sentry, expo, moment, react, react-native, and react-native-communications.
* Including the complete emulator logcat here:
```java
06-25 18:00:44.369 6832-6848/com.company.app E/dalvikvm: Could not find class 'android.app.job.JobScheduler', referenced from method com.google.android.gms.internal.agz.z
06-25 18:00:44.379 6832-6848/com.company.app E/dalvikvm: Could not find class 'android.app.job.JobScheduler', referenced from method com.google.android.gms.internal.agz.a
06-25 18:00:44.839 6832-6832/com.company.app E/dalvikvm: Could not find class 'android.app.ActivityManager$AppTask', referenced from method host.exp.exponent.d.j.a
06-25 18:00:44.849 6832-6832/com.company.app E/dalvikvm: Could not find class 'android.app.ActivityManager$AppTask', referenced from method host.exp.exponent.d.j.s
06-25 18:00:44.849 6832-6832/com.company.app E/dalvikvm: Could not find class 'android.app.ActivityManager$AppTask', referenced from method host.exp.exponent.d.j.a
06-25 18:00:45.689 6832-6832/com.company.app E/eglCodecCommon: glUtilsParamSize: unknow param 0x00008cdf
    glUtilsParamSize: unknow param 0x00008824
06-25 18:00:45.689 6832-6832/com.company.app E/EGL_emulation: tid 6832: eglSurfaceAttrib(1199): error 0x3009 (EGL_BAD_MATCH)
06-25 18:00:46.099 6832-6832/com.company.app E/a: Map already contains entry for key experienceIdSetForActivity. Ignoring.
06-25 18:00:46.799 6832-6832/com.company.app E/dalvikvm: Could not find class 'android.app.NotificationChannelGroup', referenced from method host.exp.exponent.notifications.c.a
06-25 18:00:47.569 6832-6905/com.company.app E/dalvikvm: Could not find class 'android.support.v4.b.a.a$1', referenced from method android.support.v4.b.a.a.a
06-25 18:00:47.569 6832-6905/com.company.app E/dalvikvm: Could not find class 'android.hardware.fingerprint.FingerprintManager$CryptoObject', referenced from method android.support.v4.b.a.a.a
06-25 18:00:47.569 6832-6905/com.company.app E/dalvikvm: Could not find class 'android.hardware.fingerprint.FingerprintManager$CryptoObject', referenced from method android.support.v4.b.a.a.a
06-25 18:00:47.569 6832-6905/com.company.app E/dalvikvm: Could not find class 'android.hardware.fingerprint.FingerprintManager$CryptoObject', referenced from method android.support.v4.b.a.a.a
06-25 18:00:47.569 6832-6905/com.company.app E/dalvikvm: Could not find class 'android.hardware.fingerprint.FingerprintManager', referenced from method android.support.v4.b.a.a.b
06-25 18:00:47.729 6832-6905/com.company.app E/dalvikvm: Could not find class 'android.security.keystore.KeyGenParameterSpec$Builder', referenced from method versioned.host.exp.exponent.modules.api.SecureStoreModule$AESEncrypter.initializeKeyStoreEntry
06-25 18:00:47.949 6832-6832/com.company.app E/EGL_emulation: tid 6832: eglSurfaceAttrib(1199): error 0x3009 (EGL_BAD_MATCH)
06-25 18:00:48.129 6832-6832/com.company.app E/a: Map already contains entry for key experienceIdSetForActivity. Ignoring.
06-25 18:00:48.339 6832-6832/com.company.app E/EGL_emulation: tid 6832: eglSurfaceAttrib(1199): error 0x3009 (EGL_BAD_MATCH)
06-25 18:00:48.839 6832-6832/com.company.app E/EGL_emulation: tid 6832: eglSurfaceAttrib(1199): error 0x3009 (EGL_BAD_MATCH)
06-25 18:00:49.439 6832-6832/com.company.app E/EGL_emulation: tid 6832: eglSurfaceAttrib(1199): error 0x3009 (EGL_BAD_MATCH)
06-25 18:00:50.379 6832-6832/com.company.app E/EGL_emulation: tid 6832: eglSurfaceAttrib(1199): error 0x3009 (EGL_BAD_MATCH)
06-25 18:00:51.439 6832-6832/com.company.app E/EGL_emulation: tid 6832: eglSurfaceAttrib(1199): error 0x3009 (EGL_BAD_MATCH)
06-25 18:00:53.739 6832-6942/com.company.app E/unknown:ViewManager: Error while updating prop borderBottomWidth
    java.lang.IllegalArgumentException: argument 1 should have type int, got null
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:515)
        at com.facebook.react.uimanager.ViewManagersPropertyCache$PropSetter.updateShadowNodeProp(ViewManagersPropertyCache.java:107)
        at com.facebook.react.uimanager.ViewManagerPropertyUpdater$FallbackShadowNodeSetter.setProperty(ViewManagerPropertyUpdater.java:154)
        at com.facebook.react.uimanager.ViewManagerPropertyUpdater.updateProps(ViewManagerPropertyUpdater.java:58)
        at com.facebook.react.uimanager.ReactShadowNodeImpl.updateProperties(ReactShadowNodeImpl.java:378)
        at com.facebook.react.uimanager.UIImplementation.createView(UIImplementation.java:289)
        at com.facebook.react.uimanager.UIManagerModule.createView(UIManagerModule.java:366)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:515)
        at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
        at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:160)
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
        at android.os.Handler.handleCallback(Handler.java:733)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:29)
        at android.os.Looper.loop(Looper.java:136)
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:192)
        at java.lang.Thread.run(Thread.java:841)
06-25 18:00:53.799 6832-6909/com.company.app E/unknown:ViewManager: Error while updating prop borderBottomWidth
    java.lang.IllegalArgumentException: argument 1 should have type int, got null
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:515)
        at com.facebook.react.uimanager.ViewManagersPropertyCache$PropSetter.updateShadowNodeProp(ViewManagersPropertyCache.java:107)
        at com.facebook.react.uimanager.ViewManagerPropertyUpdater$FallbackShadowNodeSetter.setProperty(ViewManagerPropertyUpdater.java:154)
        at com.facebook.react.uimanager.ViewManagerPropertyUpdater.updateProps(ViewManagerPropertyUpdater.java:58)
        at com.facebook.react.uimanager.ReactShadowNodeImpl.updateProperties(ReactShadowNodeImpl.java:378)
        at com.facebook.react.uimanager.UIImplementation.createView(UIImplementation.java:289)
        at com.facebook.react.uimanager.UIManagerModule.createView(UIManagerModule.java:366)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:515)
        at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
        at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:160)
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
        at android.os.Handler.handleCallback(Handler.java:733)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:29)
        at android.os.Looper.loop(Looper.java:136)
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:192)
        at java.lang.Thread.run(Thread.java:841)
06-25 18:00:55.999 6832-6963/com.company.app E/unknown:ViewManager: Error while updating prop top
    java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:515)
        at com.facebook.react.uimanager.ViewManagersPropertyCache$PropSetter.updateShadowNodeProp(ViewManagersPropertyCache.java:107)
        at com.facebook.react.uimanager.ViewManagerPropertyUpdater$FallbackShadowNodeSetter.setProperty(ViewManagerPropertyUpdater.java:154)
        at com.facebook.react.uimanager.ViewManagerPropertyUpdater.updateProps(ViewManagerPropertyUpdater.java:58)
        at com.facebook.react.uimanager.ReactShadowNodeImpl.updateProperties(ReactShadowNodeImpl.java:378)
        at com.facebook.react.uimanager.UIImplementation.createView(UIImplementation.java:289)
        at com.facebook.react.uimanager.UIManagerModule.createView(UIManagerModule.java:366)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:515)
        at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
        at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:160)
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
        at android.os.Handler.handleCallback(Handler.java:733)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:29)
        at android.os.Looper.loop(Looper.java:136)
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:192)
        at java.lang.Thread.run(Thread.java:841)
     Caused by: java.lang.IllegalStateException: This dynamic value has been recycled
        at com.facebook.react.bridge.DynamicFromMap.isNull(DynamicFromMap.java:46)
        at com.facebook.react.uimanager.LayoutShadowNode$MutableYogaValue.setFromDynamic(LayoutShadowNode.java:48)
        at com.facebook.react.uimanager.LayoutShadowNode.setPositionValues(LayoutShadowNode.java:693)
        at java.lang.reflect.Method.invokeNative(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:515) 
        at com.facebook.react.uimanager.ViewManagersPropertyCache$PropSetter.updateShadowNodeProp(ViewManagersPropertyCache.java:107) 
        at com.facebook.react.uimanager.ViewManagerPropertyUpdater$FallbackShadowNodeSetter.setProperty(ViewManagerPropertyUpdater.java:154) 
        at com.facebook.react.uimanager.ViewManagerPropertyUpdater.updateProps(ViewManagerPropertyUpdater.java:58) 
        at com.facebook.react.uimanager.ReactShadowNodeImpl.updateProperties(ReactShadowNodeImpl.java:378) 
        at com.facebook.react.uimanager.UIImplementation.createView(UIImplementation.java:289) 
        at com.facebook.react.uimanager.UIManagerModule.createView(UIManagerModule.java:366) 
        at java.lang.reflect.Method.invokeNative(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:515) 
        at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372) 
        at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:160) 
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method) 
        at android.os.Handler.handleCallback(Handler.java:733) 
        at android.os.Handler.dispatchMessage(Handler.java:95) 
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:29) 
        at android.os.Looper.loop(Looper.java:136) 
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:192) 
        at java.lang.Thread.run(Thread.java:841) 
06-25 18:00:59.069 6832-6832/com.company.app E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.company.app, PID: 6832
    java.lang.RuntimeException: com.facebook.react.uimanager.IllegalViewOperationException: ViewManager for tag 179 could not be found
        at com.facebook.react.bridge.ReactContext.handleException(ReactContext.java:311)
        at com.facebook.react.uimanager.GuardedFrameCallback.doFrame(GuardedFrameCallback.java:31)
        at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:134)
        at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(ChoreographerCompat.java:105)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:759)
        at android.view.Choreographer.doCallbacks(Choreographer.java:574)
        at android.view.Choreographer.doFrame(Choreographer.java:543)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:747)
        at android.os.Handler.handleCallback(Handler.java:733)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:136)
        at android.app.ActivityThread.main(ActivityThread.java:5017)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:515)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
        at dalvik.system.NativeStart.main(Native Method)
     Caused by: com.facebook.react.uimanager.IllegalViewOperationException: ViewManager for tag 179 could not be found
        at com.facebook.react.uimanager.NativeViewHierarchyManager.resolveViewManager(NativeViewHierarchyManager.java:108)
        at com.facebook.react.uimanager.NativeViewHierarchyManager.manageChildren(NativeViewHierarchyManager.java:276)
        at com.facebook.react.uimanager.UIViewOperationQueue$ManageChildrenOperation.execute(UIViewOperationQueue.java:179)
        at com.facebook.react.uimanager.UIViewOperationQueue$1.run(UIViewOperationQueue.java:821)
        at com.facebook.react.uimanager.UIViewOperationQueue.flushPendingBatches(UIViewOperationQueue.java:928)
        at com.facebook.react.uimanager.UIViewOperationQueue.access$2100(UIViewOperationQueue.java:46)
        at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:988)
        at com.facebook.react.uimanager.GuardedFrameCallback.doFrame(GuardedFrameCallback.java:29)
        at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:134) 
        at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(ChoreographerCompat.java:105) 
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:759) 
        at android.view.Choreographer.doCallbacks(Choreographer.java:574) 
        at android.view.Choreographer.doFrame(Choreographer.java:543) 
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:747) 
        at android.os.Handler.handleCallback(Handler.java:733) 
        at android.os.Handler.dispatchMessage(Handler.java:95) 
        at android.os.Looper.loop(Looper.java:136) 
        at android.app.ActivityThread.main(ActivityThread.java:5017) 
        at java.lang.reflect.Method.invokeNative(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:515) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595) 
        at dalvik.system.NativeStart.main(Native Method) 
```

### Environment
- **Node.js version**: 9.3.0
- **React Native version**: "https://github.com/expo/react-native/archive/sdk-28.0.0.tar.gz"
- **React Native platform + platform version**:  Android SDK 19

### react-native-twilio-video-webrtc
**Version**: master

**Comment by slycoder** [comment]
Could you be hitting the dalvik method limit (https://developer.android.com/studio/build/multidex)?  I ended up having to run proguard (even on debug builds) in order to ensure that things work.

**Comment by slvtrs** [comment]
Thanks for the quick reply @slycoder 
We detached from expo and so were able to add multidex via the 3rd option from the doc you linked.
That seems to have helped, but the issue persists and actually seems it may be stemming from expo's new sdk on older Android sdks- still troubleshooting.
Much appreciated! I'll close for now as this doesn't seem to be an issue with react-native-twilio-video-webrtc
