### ISSUE TITLE
`TwilioVideoPreview` has no propType for native prop `RNTwilioVideoPreview.scaleType` of native type `String`

### ISSUE THREAD

**Issue by fastmanu** [blackuy/react-native-twilio-video-webrtc#188]
### Steps to reproduce
1. Updated to latest version
2. Start Video conversation on Android

### Expected behaviour
Video conversation should start. This code actually works on ios.

### Actual behaviour
I get following error, only on android:

```
Error: Error: Error: Error: TwilioVideoPreview has no propType for native prop RNTwilioVideoPreview.scaleType of native type String
If you haven't changed this prop yourself, this usually means that your versions of the native code and JavaScript code are out of sync. Updating both should make this error go away.

This error is located at:
    in RNTwilioVideoPreview (at TwilioVideoLocalView.android.js:21)
    in TwilioVideoPreview (at VideoConf.js:319)
    in RCTView (at View.js:60)
    in View (at VideoConf.js:297)
    [...]
```

VideoConf.js:319 contains: 

```
<TwilioVideoLocalView
  enabled={true}
  style={[styles.localVideo, {backgroundColor:'#CCC'}]}
/>
```

build.gradle contains:

```
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
```

Any help would be appreciated.

### Environment
- **Node.js version**: v8.11.3
- **React Native version**: 0.55.4
- **React Native platform + platform version**: Android

### react-native-twilio-video-webrtc
**Version**: master

**Comment by slycoder** [comment]
Hm, I wasn't able to repro this on master.  Sure you don't have either the java or the js out of date?

**Comment by fastmanu** [comment]
I did `rm -rf node_modules/` this morning, followed by `npm install`. Didn't help. Any advice about how can i be sure that the java side is up-to-date??

**Comment by fastmanu** [comment]
Ok so y played a bit around and uncommented following line in _gradle.properties_ :
(i commented this on to be able to build)
`android.enableAapt2=false`

The result is that react-native run-android is unable to build and hits following error (same as #183) :

```
ERROR: In <declare-styleable> VideoView, unable to find attribute overlaySurface


> Task :app:processDebugResources
Failed to execute aapt
com.android.ide.common.process.ProcessException: Failed to execute aapt
        at com.android.builder.core.AndroidBuilder.processResources(AndroidBuilder.java:796)
        at com.android.build.gradle.tasks.ProcessAndroidResources.invokeAaptForSplit(ProcessAndroidResources.java:551)
        at com.android.build.gradle.tasks.ProcessAndroidResources.doFullTaskAction(ProcessAndroidResources.java:285)
        at com.android.build.gradle.internal.tasks.IncrementalTask.taskAction(IncrementalTask.java:109)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
        at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$IncrementalTaskAction.doExecute(DefaultTaskClassInfoStore.java:173)
        at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.execute(DefaultTaskClassInfoStore.java:134)
        at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.execute(DefaultTaskClassInfoStore.java:121)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:122)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:197)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:107)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:111)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:92)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:70)
        at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:63)
        at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:88)
        at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:52)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
        at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.run(DefaultTaskGraphExecuter.java:248)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:197)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:107)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:241)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:230)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.processTask(DefaultTaskPlanExecutor.java:124)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.access$200(DefaultTaskPlanExecutor.java:80)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:105)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:99)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.execute(DefaultTaskExecutionPlan.java:625)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.executeWithTask(DefaultTaskExecutionPlan.java:580)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.run(DefaultTaskPlanExecutor.java:99)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
Caused by: java.util.concurrent.ExecutionException: com.android.ide.common.process.ProcessException: Error while executing process /Users/username/Library/Android/sdk/build-tools/27.0.3/aapt with arguments {package -f --no-crunch -I /Users/username/Library/Android/sdk/platforms/android-27/android.jar -M /Users/username/Videoproject/android/app/build/intermediates/manifests/full/debug/AndroidManifest.xml -S /Users/username/Videoproject/android/app/build/intermediates/res/merged/debug -m -J /Users/username/Videoproject/android/app/build/generated/source/r/debug -F /Users/username/Videoproject/android/app/build/intermediates/res/debug/resources-debug.ap_ --custom-package com.Videoproject -0 apk --output-text-symbols /Users/username/Videoproject/android/app/build/intermediates/symbols/debug --no-version-vectors}
        at com.google.common.util.concurrent.AbstractFuture.getDoneValue(AbstractFuture.java:503)
        at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:482)
        at com.google.common.util.concurrent.AbstractFuture$TrustedFuture.get(AbstractFuture.java:79)
        at com.android.builder.core.AndroidBuilder.processResources(AndroidBuilder.java:794)
        ... 41 more
Caused by: com.android.ide.common.process.ProcessException: Error while executing process /Users/username/Library/Android/sdk/build-tools/27.0.3/aapt with arguments {package -f --no-crunch -I /Users/username/Library/Android/sdk/platforms/android-27/android.jar -M /Users/username/Videoproject/android/app/build/intermediates/manifests/full/debug/AndroidManifest.xml -S /Users/username/Videoproject/android/app/build/intermediates/res/merged/debug -m -J /Users/username/Videoproject/android/app/build/generated/source/r/debug -F /Users/username/Videoproject/android/app/build/intermediates/res/debug/resources-debug.ap_ --custom-package com.Videoproject -0 apk --output-text-symbols /Users/username/Videoproject/android/app/build/intermediates/symbols/debug --no-version-vectors}
        at com.android.build.gradle.internal.process.GradleProcessResult.buildProcessException(GradleProcessResult.java:73)
        at com.android.build.gradle.internal.process.GradleProcessResult.assertNormalExitValue(GradleProcessResult.java:48)
        at com.android.builder.internal.aapt.AbstractProcessExecutionAapt$1.onSuccess(AbstractProcessExecutionAapt.java:78)
        at com.android.builder.internal.aapt.AbstractProcessExecutionAapt$1.onSuccess(AbstractProcessExecutionAapt.java:74)
        at com.google.common.util.concurrent.Futures$CallbackListener.run(Futures.java:1237)
        at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
        at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:911)
        at com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:822)
        at com.google.common.util.concurrent.AbstractFuture.set(AbstractFuture.java:664)
        at com.google.common.util.concurrent.SettableFuture.set(SettableFuture.java:48)
        at com.android.build.gradle.internal.process.GradleProcessExecutor$1.run(GradleProcessExecutor.java:58)
Caused by: org.gradle.process.internal.ExecException: Process 'command '/Users/username/Library/Android/sdk/build-tools/27.0.3/aapt'' finished with non-zero exit value 1
        at org.gradle.process.internal.DefaultExecHandle$ExecResultImpl.assertNormalExitValue(DefaultExecHandle.java:380)
        at com.android.build.gradle.internal.process.GradleProcessResult.assertNormalExitValue(GradleProcessResult.java:46)
        ... 9 more
```

**Comment by fastmanu** [comment]
Ok so i rolled back some commits to figure out at which point this behaviour started for me: 157e6a7da5e74c142853982463614f6341fe79f2 is the last commit that i'm able to compile and run

**Comment by slycoder** [comment]
Interesting.  So setting `android.enableAapt2` to `false` causes a whole bunch of problems; I recall it being needed for certain older versions of RN but it shouldn't be used any more AFAIK.

Out of curiosity, if you're on master and you set scaleType to something on the local video view, does the error still occur?

**Comment by fastmanu** [comment]
I do not have had any scaleType prop on `<TwilioVideoLocalView>` or `<TwilioVideoParticipantView>` while encourting the error but indeed tried to add some scaleType prop like this: 

```
<TwilioVideoParticipantView
  scaleType='fit'
  style={styles.remoteVideo}
  key={trackSid}
  trackIdentifier={trackIdentifier}
/>
```

...without any effect.

**Comment by cKurultayKalkan** [comment]
+1. Same Problem on ios.

**Comment by slycoder** [comment]
Does someone have a repo with a reproducible example?  I can't seem to get the same error.

**Comment by Praxey** [comment]
Hello, 

For Android, at least, I think I have identified the problem.

Please go into the Android files at android/src/main/java/com/twiliorn/library

Open TwilioRemotePreviewManager.java.

Line 31 which reads:
public void setScaleType(TwilioVideoPreview view, @Nullable String scaleType)....

Change to:
public void setScaleType(TwilioRemotePreview view, @Nullable String scaleType)...

Let me know if that works and I'll get the code updated.

**Comment by cKurultayKalkan** [comment]
Does anyone has a solution for iOS devices?

**Comment by TuanPi** [comment]
+1. Same Problem on ios.

**Comment by slycoder** [comment]
Do you have a stacktrace for iOS?

**Comment by NilsonLima** [comment]
Solved here for android by adding "scaleType" in the propTypes of "TwilioVideoPreview" in file "TwilioVideoLocalView.android.js"

So, this is my file right now:
`
/**
 * Component for Twilio Video local views.
 *
 * Authors:
 *   Jonathan Chang <slycoder@gmail.com>
 */

import {
  requireNativeComponent,
  View
} from 'react-native'
import React from 'react'
import PropTypes from 'prop-types'

const propTypes = {
  ...View.propTypes,
  scaleType: PropTypes.string
}

class TwilioVideoPreview extends React.Component {
  render () {
    return (
      <NativeTwilioVideoPreview {...this.props} />
    )
  }
}

TwilioVideoPreview.propTypes = propTypes

const NativeTwilioVideoPreview = requireNativeComponent(
  'RNTwilioVideoPreview',
  TwilioVideoPreview
)

module.exports = TwilioVideoPreview
`

**Comment by slycoder** [comment]
Ah, it's a proptype issue.  Can you send a PR with your change?
