### ISSUE TITLE
Android App Crashed

### ISSUE THREAD

**Issue by mertbuldur** [blackuy/react-native-twilio-video-webrtc#278]
the project works without any error in ios but it throws out from the application in android part and does not give error

React Native Version: 0.60.2

**Comment by slycoder** [comment]
Are you running on device or emulator? Can you share your logcat logs?

**Comment by nisarnh** [comment]
I have the same problem, when it run on android and click connect app automatically closed.
no errors shown

**Comment by RatebSeirawan** [comment]
+1

**Comment by RatebSeirawan** [comment]
My flipper output ->

Name: FATAL EXCEPTION: main

Reason: java.lang.NoSuchMethodError: No static method create()Lorg/webrtc/EglBase; in class Lorg/webrtc/EglBase; or its super classes (declaration of 'org.webrtc.EglBase' appears in /data/app/com.tsapp-h2aaGlRCrdKVKcfSItoFrA==/base.apk)

Stacktrace

java.lang.NoSuchMethodError: No static method create()Lorg/webrtc/EglBase; in class Lorg/webrtc/EglBase; or its super classes (declaration of 'org.webrtc.EglBase' appears in /data/app/com.tsapp-h2aaGlRCrdKVKcfSItoFrA==/base.apk)

at com.twilio.video.EglBaseProvider.<init>(EglBaseProvider.java:93)

at com.twilio.video.EglBaseProvider.instance(EglBaseProvider.java:37)

at com.twilio.video.MediaFactory.instance(MediaFactory.java:50)

at com.twilio.video.LocalAudioTrack.create(LocalAudioTrack.java:99)

at com.twilio.video.LocalAudioTrack.create(LocalAudioTrack.java:43)

at com.twiliorn.library.CustomTwilioVideoView.createLocalMedia(CustomTwilioVideoView.java:224)

at com.twiliorn.library.CustomTwilioVideoView.connectToRoomWrapper(CustomTwilioVideoView.java:344)

at com.twiliorn.library.CustomTwilioVideoViewManager.receiveCommand(CustomTwilioVideoViewManager.java:74)

at com.twiliorn.library.CustomTwilioVideoViewManager.receiveCommand(CustomTwilioVideoViewManager.java:40)

at com.facebook.react.uimanager.NativeViewHierarchyManager.dispatchCommand(NativeViewHierarchyManager.java:788)

at com.facebook.react.uimanager.UIViewOperationQueue$DispatchCommandOperation.execute(UIViewOperationQueue.java:279)

at com.facebook.react.uimanager.UIViewOperationQueue$1.run(UIViewOperationQueue.java:792)

at com.facebook.react.uimanager.UIViewOperationQueue.flushPendingBatches(UIViewOperationQueue.java:903)

at com.facebook.react.uimanager.UIViewOperationQueue.access$2400(UIViewOperationQueue.java:43)

at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:963)

at com.facebook.react.uimanager.GuardedFrameCallback.doFrame(GuardedFrameCallback.java:29)

at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:175)

at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(ChoreographerCompat.java:85)

I've added permission manually so that should not be the cause.

**Comment by slycoder** [comment]
Thanks.  That helps a lot!  After quick googling it seems like this is an issue with the underlying twilio library, and there are some suggested fixes there:

https://github.com/twilio/video-quickstart-android/issues/430

**Comment by akshay-squareboat** [comment]
How to resolve it in React Native. Do we need to make changes to gradle or any other changes. That solution isn't specific to Native.

**Comment by slycoder** [comment]
Yeah, looks like you can just tweak your gradle scripts.

**Comment by fachreza73** [comment]
thanks @slycoder 

change minSdkVersion to 24 solve my issue
