### ISSUE TITLE
Disconnect and flipCamera not working on Android since v6 upgrade

### ISSUE THREAD

**Issue by James3432** [blackuy/react-native-twilio-video-webrtc#544]
Preface: I've been using this library for a couple of years and am broadly familiar with it. The following issue does not occur when reverting back to before #452 

### Steps to reproduce
1. Setup basic example as per instructions
2. Try to call this.twilioRef.current.disconnect()   (but similar bug with .flipCamera() )

### Expected behaviour
The video should stop and a disconnection event should fire

### Actual behaviour
The video freezes, but audio continues to stream to the room. No events fire. No errors are logged.

### Environment
- **Node.js version**: 14.15.4
- **React Native version**: 0.65.1
- **React Native platform + platform version**: Android 11

### react-native-twilio-video-webrtc
**Version**: master

**Comment by tylerssn** [comment]
Any progress on this James?

**Comment by James3432** [comment]
> Any progress on this James?

No, I'm afraid I reverted to an older version and didn't have time to investigate myself. I don't know if any recent changes might have fixed the issue - I'll check again when I have time.

**Comment by James3432** [comment]
Update:  disconnect() is now working (with the latest version of this library and RN 0.66.1).
However, calls to flipCamera() still fail with the following error being thrown:

java.lang.IllegalArgumentException: Camera ID must be different from current camera ID
        at com.twilio.video.Preconditions.checkArgument(Preconditions.java:131)
        at com.twilio.video.CameraCapturer.switchCamera(CameraCapturer.java:360)
        at com.twiliorn.library.CustomTwilioVideoView.switchCamera(CustomTwilioVideoView.java:615)

(most recently tested on a Pixel 3a running Android 11)

**Comment by slycoder** [comment]
Oof, does this device have an actual front and back facing camera?  If possible could you log breakpoint on the values of `frontFacingDevice` and `backFacingDevice` in `buildDeviceInfo`.

**Comment by vikrambombhi** [comment]
@slycoder I'm seeing the same issue. Are there docs on how to build this project for development? I can do some debugging but need help getting setup

**Comment by slycoder** [comment]
In the case of android, each of the dependent projects should appear under the 'projects' pane of Android Studio.  If you navigate to react-native-twilio-video-webrtc, you should be able to edit the java files and have those changes reflected in your built project.  Hope that helps!
