### ISSUE TITLE
Play Store Vulnerability Error

### ISSUE THREAD

**Issue by GavinConnolly** [blackuy/react-native-twilio-video-webrtc#642]
In the past 24 hours we've had this error show up regarding the WebRTC version:

![Screenshot 2022-10-20 at 15.18.12.png](https://user-images.githubusercontent.com/522905/196976339-8eb6f50a-88dd-4dde-9270-9b53a786ef59.png)

Any one else receiving this error? 

### Steps to reproduce
Submit V2.1.0 Android app

**Comment by nickfera** [comment]
Yep, sent our app this morning and received the same error.

**Comment by owenadley** [comment]
Same error here.

**Comment by adesun2k** [comment]
Same here

**Comment by MarcDerhammer** [comment]
It seems that the WebRTC team stopped publishing official binaries.  One of the bullets [in the article](https://support.google.com/faqs/answer/12577537) mentions this:

> Note that pre-built WebRTC binaries have been deprecated for some time. Developers must build from source to get the latest updates.

If you're OK with using unofficial binaries, [this repo](https://github.com/rno/WebRTC) has been building and publishing them (among a few others)

The alternative is adjusting `react-native-twilio-video-webrtc` to build the binaries from source, however one easy solution is to just use one of these published builds.

You can use [patch package](https://www.npmjs.com/package/patch-package) to accomplish this.

1. Setup [patch package](https://www.npmjs.com/package/patch-package) per its instructions
2. In your project, open `node_modules/react-native-twilio-video-webrtc/android/build.gradle`
3. Replace
`implementation 'org.webrtc:google-webrtc:1.0.30039'`
with
`implementation 'com.dafruits:webrtc:106.0.0'`
(or whatever other published binary you like)
4. In your base directory execute `npx patch-package react-native-twilio-video-webrtc` to apply the patch in the future as well
5. Rebuild your Android app and test it 

Google no longer is mad about the bad WebRTC Version used in my app.  

This also fixed a few other Android-specific problems I was facing while using this library.

Hope this helps somebody :)

**Comment by slycoder** [comment]
https://github.com/twilio/video-quickstart-android/issues/731

**Comment by jagamypriera** [comment]
@GavinConnolly Got same issue here


>    `implementation 'com.dafruits:webrtc:106.0.0'`

@MarcDerhammer Tried using this library, but I got this error when video calling 
```bash
java.lang.NullPointerException: Attempt to invoke virtual method 'long com.twilio.video.VideoSinkHintsProducer.getSinkHintsId()' on a null object reference
        at com.twilio.video.VideoView.getSinkHintsId(VideoView.java:223)
        at com.twilio.video.RemoteVideoTrack.removeSink(RemoteVideoTrack.java:106)
        at com.twiliorn.library.CustomTwilioVideoView.registerPrimaryVideoView(CustomTwilioVideoView.java:1318)
        at com.twiliorn.library.TwilioRemotePreview.<init>(TwilioRemotePreview.java:25)
        at com.twiliorn.library.TwilioRemotePreviewManager.createViewInstance(TwilioRemotePreviewManager.java:61)
        at com.twiliorn.library.TwilioRemotePreviewManager.createViewInstance(TwilioRemotePreviewManager.java:24)
        at com.facebook.react.uimanager.ViewManager.createViewInstance(ViewManager.java:183)
        at com.facebook.react.uimanager.ViewManager.createView(ViewManager.java:115)
        at com.facebook.react.uimanager.NativeViewHierarchyManager.createView(NativeViewHierarchyManager.java:281)
        at com.facebook.react.uimanager.UIViewOperationQueue$CreateViewOperation.execute(UIViewOperationQueue.java:194)
        at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.dispatchPendingNonBatchedOperations(UIViewOperationQueue.java:1110)
        at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:1081)
        at com.facebook.react.uimanager.GuardedFrameCallback.doFrame(GuardedFrameCallback.java:29)
        at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:175)
        at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(ChoreographerCompat.java:85)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:947)
        at android.view.Choreographer.doCallbacks(Choreographer.java:761)
        at android.view.Choreographer.doFrame(Choreographer.java:693)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:935)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```
